# Generated by Django 3.1.5 on 2021-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('registration_type', models.CharField(max_length=15)),
                ('no_of_people', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('event_poster_link', models.URLField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('registration_end_date', models.DateField()),
                ('registration_end_time', models.TimeField()),
                ('host_emailid', models.EmailField(max_length=254)),
                ('participants', models.ManyToManyField(to='eventManagementApp.Participant')),
            ],
        ),
    ]
