# Generated by Django 3.1.5 on 2021-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagementApp', '0002_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='Default event description'),
        ),
    ]
