# Generated by Django 3.1.5 on 2021-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagementApp', '0003_auto_20210129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='host_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='eventManagementApp.Participant'),
        ),
    ]
